### ISSUE TITLE
markbot will not load screenshots

### ISSUE THREAD

**Issue by Jessica3860** [Jessica3860/using-svg-icons#1]
hi Wendy @wendywarren, hope you are well. 

I have tried multiple times to get markbot to load the screenshots for this assignment without prevail. Therefor, is there anything else I can try to get markbot to submit this assignment? 

thank you, 
-Jessica 

(the screenshots from markbot, saying everything else is correct)
![image](https://user-images.githubusercontent.com/83955882/155305036-7eef5e32-a4b0-4c72-bb9d-547fa45de844.png)
![image](https://user-images.githubusercontent.com/83955882/155306824-fe2af12c-c469-419d-9e58-0ae5e856f759.png)
![image](https://user-images.githubusercontent.com/83955882/155307731-b9fd138b-2ab9-4775-9c28-e5bce94679dc.png)

**Comment by wendywarren** [comment]
Hi @Jessica3860,

I'm not sure why Markbot has decided to give you such a hard time lately. I've checked your latest deployment and you did it correctly so I will manually update your grade on the progress site right now.

Thanks,
Wendy

**Comment by Jessica3860** [comment]
thank you so much! @wendywarren
